### ISSUE TITLE
Add some example csv files to drag and drop

### ISSUE THREAD

**Issue by nikita-galileo** [rungalileo/bulk-labeling#5]
People might not have a csv dataset on hand to paste into this drag and drop. Maybe we can add a couple of example ones above it that can be drag and dropped like folks often do with Gradio demos?

<img width="339" alt="Screen Shot 2022-10-03 at 4 55 17 PM" src="https://user-images.githubusercontent.com/83978491/193706109-878a1495-6ff9-4208-af47-faf27d238268.png">

**Comment by Ben-Epstein** [comment]
done! https://github.com/rungalileo/bulk-labeling/commit/105bcc710cb68379904ec8e95022a48b879e7920
